name: MQ Queue Management

on:
  push:
    branches: [main]
    paths:
      - 'mqsc/**/*.mqsc'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

env:
  MQ_NAMESPACE: ibm-mq-ns
  QMGR_NAME: secureapphelm

jobs:
  deploy-queues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
      
      - name: Get MQ Pod
        run: |
          MQ_POD=$(kubectl get pods -n ${{ env.MQ_NAMESPACE }} -o jsonpath='{.items[0].metadata.name}')
          echo "MQ_POD=$MQ_POD" >> $GITHUB_ENV
          echo "Found pod: $MQ_POD"
      
      - name: Apply Queues
        run: |
          ENV="${{ github.event.inputs.environment || 'dev' }}"
          
          for mqsc_file in ./mqsc/${ENV}/*.mqsc; do
            echo "Applying $(basename $mqsc_file)..."
            kubectl exec -i ${{ env.MQ_POD }} -n ${{ env.MQ_NAMESPACE }} -- \
              runmqsc ${{ env.QMGR_NAME }} < "$mqsc_file"
          done
      
      - name: List Queues
        if: always()
        run: |
          echo "Current queues:"
          kubectl exec -i ${{ env.MQ_POD }} -n ${{ env.MQ_NAMESPACE }} -- \
            bash -c "echo 'DISPLAY QLOCAL(*)' | runmqsc ${{ env.QMGR_NAME }}" || true